### PR TITLE
Add error handling for invalid events added directly into json storage files

### PR DESCRIPTION
**Pull request by cowlinn**
If the user tries to edit the json event files, there are additional safeguards in place to ensure he doesn't add "illegal" events.

`Ilegal Events` includes the following: 
1. Adding an event that specifies a person who's name is not in LTNS
2. Adding an event with a time that overlaps with another event

Both types of events should be invalid additions, via CLI in LTNS, OR by editting the JSON file directly

This requires persons to be loaded before events in the code logic*

### CODE REVIEW

**Comment by loyhongshenggg** [comment]
image

Should not be addressbook for error message

**Comment by loyhongshenggg** [comment]
image

Tested, I suppose this is the correct result! Good job!

**Comment by cowlinn** [comment]
> image (Duplicated user test)
> 
> image (Banana man test) (Adding client that does not exist test)
> 
> image (Overlapping timings test)
> 
> Tested, I suppose this is the correct result! Good job!

Thank you so much for the detailed testing! Changes to display rectified (I also looked through more of the javadocs / error codes for the commands specifically to remove more traces of AddressBook snuck in here and there)

**Comment by loyhongshenggg** [comment]
Nice, thanks for changing the traces of addressbook hahah

**Comment by loyhongshenggg** [comment]
Tested again, LGTM!

**Pull request merged**
